---
neovim_version: 0.12.2
neovim_archive_sha256: 31cf85945cb600d96cdf69f88bc68bec814acbff50863c5546adef3a1bcef260
chezmoi_version: 2.72.2
chezmoi_binary_sha256: 64a07b2e956be7ea18a9d26cbc76aab96a8b45a6b7b6f58c41ff782a7dc361ab

qt_qmake_path: /opt/qt-everywhere-src-5.15.2/qtbase/bin/qmake

npm_language_servers:
  - name: bash-language-server
    version: 5.8.1
  - name: yaml-language-server
    version: 1.24.0
  - name: "@ansible/ansible-language-server"
    version: 26.6.0
  - name: sql-language-server
    version: 1.7.1
  - name: vscode-langservers-extracted
    version: 4.10.0

python_developer_packages:
  - basedpyright==1.40.1
  - debugpy==1.8.22
  - ruff==0.16.8
